### ISSUE TITLE
Unable to build with rust 1.6.0

### ISSUE THREAD

**Issue by VanushVaswani** [autumnai/leaf#43] opened 2016-01-28 10:48 UTC
```
cargo build
   Compiling regex-syntax v0.2.2
   Compiling rustc-serialize v0.3.16
   Compiling bitflags v0.3.2
   Compiling lazy_static v0.1.15
   Compiling glob v0.2.10
   Compiling openssl-sys v0.6.7
   Compiling kernel32-sys v0.2.1
   Compiling advapi32-sys v0.1.2
   Compiling strsim v0.3.0
   Compiling miniz-sys v0.1.7
   Compiling num_cpus v0.2.7
   Compiling byteorder v0.3.13
   Compiling clippy v0.0.23
   Compiling csv v0.14.3
   Compiling url v0.2.37
/Users/vanushv/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.23/src/lib.rs:1:1: 1:42 error: #[feature] may not be used on the stable release channel
/Users/vanushv/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.23/src/lib.rs:1 #![feature(plugin_registrar, box_syntax)]
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vanushv/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.23/src/lib.rs:2:1: 2:46 error: #[feature] may not be used on the stable release channel
/Users/vanushv/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.23/src/lib.rs:2 #![feature(rustc_private, core, collections)]
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vanushv/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.23/src/lib.rs:3:1: 3:28 error: #[feature] may not be used on the stable release channel
/Users/vanushv/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.23/src/lib.rs:3 #![feature(num_bits_bytes)]
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 3 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `clippy`.

To learn more, run the command again with --verbose.
```

**Comment by hobofan** [comment] 2016-01-28 10:53
Duplicate of #42 (#40)

**Closed by hobofan** 2016-01-28 10:53 UTC
